[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.17'
optimizer_runs = 10000

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
seploia = "${SEPOLIA_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
